### ISSUE TITLE
A problem about installing

### ISSUE THREAD

**Issue by shiqingzhangCSU** [scikit-tda/cechmate#4]

**Comment by shiqingzhangCSU** [comment]
![image](https://user-images.githubusercontent.com/44834482/54575420-0471dc80-4a2f-11e9-8be3-59412230d135.png)

**Comment by sauln** [comment]
It looks like something is going wrong when installing the dependency `phat`. Could you try installing it directly? If you get the same error, then please open an issue on that project's GitHub [here](https://github.com/xoltar/phat/issues). 

Thank you!

**Comment by ctralie** [comment]
Hello @shiqingzhangCSU, it's been a while.  Are you still having this issue?

**Comment by shiqingzhangCSU** [comment]
I have solved this problem since I switched to the ubuntu system.

**Comment by shiqingzhangCSU** [comment]
I have solved this problem since I switched to the ubuntu system.Thank you!

**Comment by ctralie** [comment]
Okay, thanks for the update.

Hmm...I'll close the issue for now, but we may still need to be mindful of installation issues on other platforms
