### ISSUE TITLE
Change `max_dim` to `maxdim`

### ISSUE THREAD

**Issue by sauln** [scikit-tda/cechmate#6]
Ripser.py uses the keyword `maxdim` while cechmate uses `max_dim`. We should standardize this across both projects. Since Ripser.py has a userbase already, I vote we change cechmate.

**Comment by ctralie** [comment]
Yes, definitely!

**Comment by ctralie** [comment]
As a related issue, cech and alpha don't have max_dim in their constructor; only base does
